# Generated by Django 5.2.15 on 2026-06-22 08:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creditaccount_creditrecharge_credittask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('llm', 'LLM'), ('tts', 'TTS'), ('asr', 'ASR'), ('vision', 'Vision'), ('video', 'Video')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('api_key', models.CharField(blank=True, max_length=240)),
                ('enabled', models.BooleanField(default=False)),
                ('price_coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
