# Generated by Django 5.2.15 on 2026-06-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('products', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('selling_points', models.TextField(blank=True)),
                ('forbidden_words', models.TextField(blank=True)),
                ('contact_hooks', models.TextField(blank=True)),
                ('style_preference', models.TextField(blank=True)),
                ('logo_or_common_assets', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='core.workspace')),
            ],
        ),
    ]
