# Generated by Django 5.2.15 on 2026-06-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=240)),
                ('content_type', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('output', 'Output')], max_length=20)),
                ('object_key', models.CharField(max_length=320, unique=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('expires_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.workspace')),
            ],
        ),
    ]
