# Generated by Django 5.2.15 on 2026-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='suggested_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
