# Generated by Django 5.2.15 on 2026-06-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asset_suggested_tags_asset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('industry', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViralSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('system', 'System'), ('workspace', 'Workspace')], default='workspace', max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('copy', models.TextField()),
                ('structure_analysis', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rewrite', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viral_samples', to='core.customerprofile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viral_samples', to='core.workspace')),
            ],
        ),
    ]
