# Generated by Django 5.2.15 on 2026-06-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_industrytemplate_viralsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('sample_ids', models.JSONField(blank=True, default=list)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('confirmed_script', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='script_drafts', to='core.customerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='script_drafts', to='core.aiprovider')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='script_drafts', to='core.industrytemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_drafts', to='core.workspace')),
            ],
        ),
    ]
