# Generated by Django 5.2.15 on 2026-06-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='audio_placeholder',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='job',
            name='source_audio_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asr_jobs', to='core.asset'),
        ),
        migrations.AddField(
            model_name='job',
            name='subtitles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='voiceover_mode',
            field=models.CharField(choices=[('none', 'No voiceover'), ('tts', 'TTS voiceover'), ('asr', 'ASR subtitles')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='voiceover_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voiceover_jobs', to='core.aiprovider'),
        ),
    ]
