# Generated by Django 5.2.15 on 2026-06-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_audio_placeholder_job_source_audio_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_jobs', to='core.asset'),
        ),
        migrations.AddField(
            model_name='job',
            name='render',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
