# Generated by Django 5.2.15 on 2026-06-24 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_job_output_asset_job_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='capability',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aiprovider'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='capability',
            field=models.CharField(choices=[('llm', 'LLM'), ('tts', 'TTS'), ('asr', 'ASR'), ('vision', 'Vision'), ('video', 'Video'), ('image', 'AI Image'), ('digital_human', 'Digital Human'), ('ai_video', 'AI Video'), ('voice_clone', 'Voice Clone'), ('comfyui', 'ComfyUI')], max_length=20),
        ),
    ]
