# Generated by Django 5.2.15 on 2026-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_capability_job_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprovider',
            name='api_key',
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='api_key_env',
            field=models.CharField(blank=True, max_length=120, verbose_name='API key env var'),
        ),
    ]
